### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by SylvainPlessis** [libqueso/queso#176]
Trying to compile with libMesh Library: Version = 0.9.3-pre (903):

../src/core/src/LibMeshOperatorBase.C: In member function 'virtual void QUESO::LibMeshOperatorBase::save_converged_evals(const std::string&) const':
../src/core/src/LibMeshOperatorBase.C:86: error: variable 'std::ofstream evals_file' has initializer but incomplete type

It compiles just fine if I turn off libmesh linkage.  I'm still not sure if it's not something with my libmesh build or a QUESO bug...

Have fun,

Sylvain
